### ISSUE TITLE
Prefixes get invisble with `-hl` in linux with konsole with bright background.

### ISSUE THREAD

**Issue by bernhardu** [bitdefender/bddisasm#109]
For some reason the `FG_White` gets completely invisble in this konsole, also the help text.
![grafik](https://github.com/user-attachments/assets/ebd68298-9b8c-496c-b403-07ab20d9d92d)
(Konsole 22.12.3, KDE Frameworks 5.103.0, Qt 5.15.8)
#

Replacing `FG_White` by the otherwise unused `FG_Cyan` would help.
![grafik](https://github.com/user-attachments/assets/f4447b6a-b4ef-4e15-b621-453b1ef88f4f)
#

Don't know if this is important enough to fix here, or if this should be addressed in konsole.

**Comment by ianichitei** [comment]
No matter the color scheme used, there can always be a terminal theme on which it would look bad. The proper way of doing this is to probably have at least two color schemes, one for dark themes, one for light themes and choose one based on the environment, but AFAIK there's no portable way of actually detecting this.

**Comment by bernhardu** [comment]
Thanks for taking a look and maintaining bddisasm, so I guess I can safely close this issue.
