### ISSUE TITLE
disasmtool_lix without specifying bits

### ISSUE THREAD

**Issue by sabastiaan** [bitdefender/bddisasm#14]
Hi there,

I notice that a decent chance exist of being able to start disasmtool_lix with only an -i or -c argument.
Even with pressing up on my shell to re-execute the last used command, it typically only takes a few tries to active the bug.
Pasting a command seems to work consistent than other options. 
However from the source code it seems like this isn't supposed to be allowed?

Kind regards,

Sebastiaan

``` ./build/disasmtool -i
>> 70 EF
0 70ef                            JO        0xfffffff1
```

**Comment by cbsirb** [comment]
It's very weird indeed, and only happens from time to time: if `bits` is missing, it somehow gets a random value.

It's a problem with the [argument parser library](https://github.com/luzhlon/argparse) used (it's old and just a fork). With [the proper one](https://github.com/jamolnng/argparse) the problems go away.
