### ISSUE TITLE
False-positive decoding on AMD64: DMINT

### ISSUE THREAD

**Issue by woodruffw** [bitdefender/bddisasm#23]
Similar to #22: bddisasm decodes `0Fh 39h` as `DMINT` when in 64-bit mode, despite being a 16/32-bit only instruction on some very old AMD Geode CPUs:

0f39 | (0 / 0) | (0 / 0) | DMINT (2 / 5)
-- | -- | -- | --

The same happens with prefixes, e.g.:

3e2636f24d0f39 | (0 / 0) | (0 / 0) | DMINT (7 / 5)
-- | -- | -- | --

Neither Intel nor AMD's documentation references `DMINT` at all. The only other major reference I could find for it is iced-x86, which documents it as 16/32 only: https://docs.rs/iced-x86/1.9.1/iced_x86/enum.Code.html#variant.Dmint

**Comment by vlutas** [comment]
Fixed.
