### ISSUE TITLE
Consider upstreaming your mishegos worker

### ISSUE THREAD

**Issue by woodruffw** [bitdefender/bddisasm#3]
Hi there!

Thanks for the shoutout to [mishegos](https://github.com/trailofbits/mishegos) in your README; I'm glad to hear that it helped in testing your decoder.

I'd definitely be interested in upstreaming the worker that you used for testing, or helping you write a new one if needed.

Let me know if there's anything I can do to help!

**Comment by vlutas** [comment]
Hello!

Thanks for your interest, and thanks for the great tool, it actually helped us pinpoint some exotic bugs in bddisasm. While it is not ready yet, we do intend to publish the worker soon, and perhaps even asking for your contribution to make it happen faster, or in a more stable form. We'll get back as soon as we have updates!

Thanks again!

**Comment by woodruffw** [comment]
That’s great to hear! Feel free to ping me once it’s ready for me to help with.

**Comment by ianichitei** [comment]
> That’s great to hear! Feel free to ping me once it’s ready for me to help with. Sent from mobile. Please excuse my brevity.

I published our changes to https://github.com/ianichitei/mishegos

I'm not sure if everything is stable yet. If you have the time, we're hoping to receive some feedback from you. 

Special thanks go to @akisari for investigating some build issues.

**Comment by woodruffw** [comment]
Fantastic! I took a quick look, and couldn't find any obvious issues 😄 

Would you mind opening a PR to the upstream repo?

**Comment by ianichitei** [comment]
I'm glad to here that. I will open a PR. I will keep this open until that PR is merged.
