### ISSUE TITLE
False-positive decoding on AMD64: PFRCPV

### ISSUE THREAD

**Issue by woodruffw** [bitdefender/bddisasm#36]
Similar to #23: `f22e0f0f5ec586` decodes as `PFRCPV mm3, qword ptr [rsi-0x3b]`, despite being a 16/32-bit only instruction that only appears on very old AMD CPUs.

f22e0f0f5ec586 | (0 / 0) | (0 / 0) | (0 / 0) | PFRCPV mm3, qword ptr [rsi-0x3b] (7 / 32) | (0 / 0)
-- | -- | -- | -- | -- | --

**Comment by vlutas** [comment]
Fixed in https://github.com/bitdefender/bddisasm/commit/98ea9e1d9a74b5e6ed050d2356cceefbc18462d4
