### ISSUE TITLE
False-positive decoding on AMD64: `FSTDW`

### ISSUE THREAD

**Issue by woodruffw** [bitdefender/bddisasm#37]
bddisasm currently decodes `4ddfe1` as `FSTDW`.

`FSTDW` is a floating point instruction that only existed on the 80387SL. As such, no modern AMD64 CPU supports it, and it can only ever possibly be valid in a 16 or 32-bit mode.

4ddfe1 | (0 / 0) | (0 / 0) | (0 / 0) | FSTDW ax (3 / 8) | (0 / 0)
-- | -- | -- | -- | -- | --

References:
* https://www.sandpile.org/x86/opc_fpu.htm
* https://docs.rs/iced-x86/1.10.0/iced_x86/enum.Code.html#variant.Fstdw_AX

**Comment by vlutas** [comment]
Fixed in https://github.com/bitdefender/bddisasm/commit/98ea9e1d9a74b5e6ed050d2356cceefbc18462d4
