### ISSUE TITLE
 JMP       qword ptr [rax+0x10] why Operand count is 2

### ISSUE THREAD

**Issue by icyfox168168** [bitdefender/bddisasm#43]
0000000000000000 ff6010                          JMP       qword ptr [rax+0x10]
        DSIZE: 64, ASIZE: 64, VLEN: -
        ISA Set: I86, Ins cat: UNCOND_BR, CET tracked: yes
        Valid modes
                R0: yes, R1: yes, R2: yes, R3: yes
                Real: yes, V8086: yes, Prot: yes, Compat: yes, Long: yes
                SMM on: yes, SMM off: yes, SGX on: yes, SGX off: yes, TSX on: yes, TSX off: yes
                VMXRoot: yes, VMXNonRoot: yes, VMXRoot SEAM: yes, VMXNonRoot SEAM: yes, VMX off: yes
        Valid prefixes
                REP: no, REPcc: no, LOCK: no
                HLE: no, XACQUIRE only: no, XRELEASE only: no
                BND: yes, BHINT: no, DNT: yes
        Operand: 0, Acc:  R-,  Type:     Memory, Size:  8, RawSize:  8, Encoding: M,
                Segment: 3, Base: 0, Displacement: 0x0000000000000010,
        Operand: 1, Acc:  -W,  Type:   Register, Size:  8, RawSize:  8, Encoding: S, RegType:               IP, RegSize:  8, RegId: 0, RegCount: 1

Read 0x1000:    jmp             qword ptr [rax + 0x10] // insn-ID: 264, insn-mnem: jmp
        Prefix:0x00 0x00 0x00 0x00
        Opcode:0xff 0x00 0x00 0x00
        rex: 0x0
        addr_size: 8
        modrm: 0x60
        modrm_offset: 0x1
        disp: 0x10
        disp_offset: 0x2
        disp_size: 0x1
        sib: 0x0
        op_count: 1
                operands[0].type: MEM
                        operands[0].mem.base: REG = rax
                        operands[0].mem.disp: 0x10
                operands[0].size: 8
                operands[0].access: READ
        Registers read: rax

**Comment by vlutas** [comment]
Because the instruction has two operands:
- the explicit **qword ptr [rax+0x10]** operand, which indicates the target of the jump;
- the implicit **RIP** operand, as the instruction modifies the instruction pointer too.

**Comment by icyfox168168** [comment]
Thank you for your answer, great design, different and other engines
