### ISSUE TITLE
lea rdx,qword ptr ds:[0x140000000] bug ?

### ISSUE THREAD

**Issue by icyfox168168** [bitdefender/bddisasm#45]
0x0000000000200000 LEA       rdx, [rel 0xfffffffffe973018]

RDX = 0xfffffffffe973018

why rdx != 0x140000000 ?

**Comment by icyfox168168** [comment]
printf("%d\n", _llen(0,0));   == 7 

ShemuEmulate  !=7

why ?      lea rax,[rip] erro

int __add = 7;
#pragma optimize( "", off )


int _llen(char* str1, char* str2)
{
    void* ret = &__add;
    return *(int*)ret;
}
#pragma optimize( "", on )

**Comment by icyfox168168** [comment]
int __add = 7;
#pragma optimize( "", off )
int _llen(char* str1, char* str2)
{
    void* ret = &__add;
    return *(int*)ret;
/*
    if (strlen(str1) > strlen(str2))
    {
       
        __add = 5;
    }
    else
    {
        __add = 6;
    }
    return strlen(str1) + strlen(str2) + __add;
*/
}
#pragma optimize( "", on )

**Comment by icyfox168168** [comment]
The asterisk of the pointer is less. The function returns to that place. I don't know why. GitHub problem

return ->(int->)ret;

**Comment by vlutas** [comment]
Not a bug. Please refer to RIP-relative addressing in the Intel Software Development Manual.
