### ISSUE TITLE
andn ecx, r9d, edi bug?

### ISSUE THREAD

**Issue by icyfox168168** [bitdefender/bddisasm#46]
"\xC4\xE2\x30\xF2\xCF"

bdd OpLength 1 OpOffset 3

andn ecx, r9d, edi
Read 0x1000:    andn            ecx, r9d, edi // insn-ID: 26, insn-mnem: andn
        Prefix:0x00 0x00 0x00 0x00
        Opcode:0xc4 0xe2 0x30 0x00
        rex: 0x40
        addr_size: 8
        modrm: 0xcf
        modrm_offset: 0x4
        disp: 0x0
        sib: 0x0
        op_count: 3

**Comment by vlutas** [comment]
Hello,

Bug where exactly?

**Comment by icyfox168168** [comment]
op count bdd is 1

capstone is 3

**Comment by vlutas** [comment]
You are confusing **OpLength**, which indicates the length, in bytes, of the opcode, with **Operands count**, which indicates the number of operands. bddisasm reports the correct number of operands - 3 explicit, and 1 implicit (the flags).
