### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [bitdefender/bddisasm#5]
I would like to point out that identifiers like “[`_MNEMONICS_H_`](https://github.com/bitdefender/bddisasm/blob/752bc626c4cfc1541441c5e507d65c3cde54f3ff/isagenerator/generate_tables.py#L1020 "Update candidate")” and “[`_TABLE_VEX_H_`](https://github.com/bitdefender/bddisasm/blob/752bc626c4cfc1541441c5e507d65c3cde54f3ff/isagenerator/generate_tables.py#L962 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by ianichitei** [comment]
This is a problem indeed. I'll take a look at it and I will change the include guards, but this will happen most likely Monday.

Speaking of C++, I think we can make another improvement and add `extern "C"` to our public headers, but that's another issue.

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/bitdefender/bddisasm/commit/049ecc0ab7975f73d413c8c15d8f7b2d05ea14bc "Don't use reserved identifiers for include guards").
