### ISSUE TITLE
ROL       rcx, 0x10,My cpu is amd, real cpu and unicorn can get 99, bddisasm get 98, but you give OF undefined conclusion

### ISSUE THREAD

**Issue by icyfox168168** [bitdefender/bddisasm#64]

**Comment by vlutas** [comment]
The OF is undefined on AMD as well for rotate/shift with count greater than one. It doesn't matter what results **you** get, those results may very well be different on other CPUs. An undefined flag cannot be set to any specific value. 

In the future, please reopen the original issue if you have further comments. Don't create a new one for each question you have, as it makes issue tracking difficult.
