### ISSUE TITLE
div qword ptr ss:[rbp]

### ISSUE THREAD

**Issue by icyfox168168** [bitdefender/bddisasm#65]
5E18  00000037C8BFB068

long long  asmadc()
{
    long long ret = 0x97C41B;
    __asm
    {
          push 0x244
          pushf
          mov rax, 0x00000037C8BFB068
          xor rdx,rdx
          div ret
          mov ret,rax

    }

    return ret;
}

"\x55\x50\x48\x89\xE5\x48\xC7\x45\x00\x1B\xC4\x97\x00\x68\x44\x02\x00\x00\x9C\x48\xB8\x68\xB0\xBF\xC8\x37\x00\x00\x00\x48\x31\xD2\x48\xF7\x75\x00\x48\x89\x45\x00\x48\x8B\x45\x00\x48\x83\xC4\x08\x5D\xC3"

**Comment by vlutas** [comment]
FaD. DIV/IDIV with 64 bit source operand is not implemented.
