### ISSUE TITLE
ND_INS_CPUID // Can provide external setting value?

### ISSUE THREAD

**Issue by icyfox168168** [bitdefender/bddisasm#73]
In this structure SHEMU_CONTEXT sets the CPUID value

**Comment by vlutas** [comment]
I could expose a new callback, similar to ShemuMemAccess, which - when set - would be called by the shemu engine on CPUID emulation. The callback implementation would then return the appropriate result in the EAX, ECX, EDX and EBX registers.

**Comment by icyfox168168** [comment]
Very nice, can be written as a generic callback? It can also be suitable for other assembly instructions that do not support
