### ISSUE TITLE
Compiling with clang-cl/gcc(mingw64)

### ISSUE THREAD

**Issue by angelfor3v3r** [bitdefender/bddisasm#77]
Hi! I was wondering if there will ever be support for clang-cl/gcc. I currently have a few issues when compiling.

The issue with clang-cl is that when you reach these lines:
https://github.com/bitdefender/bddisasm/blob/70db095765ab2066dd88dfb7bbcc42259ed167c5/bdshemu/bdshemu.c#L3109-L3120

The compiler will error saying AES features are not enabled. I'm guessing for some reason MSVC allows it, but clang-cl does not.

For GCC it's a bit more troublesome:
```
C:/Srcs/test/bddisasm/bddisasm/bddisasm.c:3516:1: error: multiple storage classes in declaration specifiers
 3516 | static __forceinline NDSTATUS
      | ^~~~~~
C:/Srcs/test/bddisasm/bddisasm/bddisasm.c:3571:1: error: multiple storage classes in declaration specifiers
 3571 | static __forceinline NDSTATUS
      | ^~~~~~
C:/Srcs/test/bddisasm/bddisasm/bddisasm.c:3602:1: error: multiple storage classes in declaration specifiers
 3602 | static __forceinline NDSTATUS
      | ^~~~~~
C:/Srcs/test/bddisasm/bddisasm/bddisasm.c:3758:1: error: multiple storage classes in declaration specifiers
 3758 | static __forceinline NDSTATUS
      | ^~~~~~
```

The library works fine when under MSVC (like the readme states) but it would be nice for these other compilers to be supported. If no fixes are planned, is there at least some suggested compiler flags to get it to work on clang-cl? I thought maybe `/clang:-maes` would suffice but I didn't bother trying because I noticed when using GCC you pass `-march=westmere` instead. Perhaps there needs to be a check if clang-cl is being used and pass extra arguments?

**Comment by a-cristi** [comment]
Hi! I'm guessing you're compiling for Windows. I haven't really used anything besides MSVC for Windows, but we support clang and GCC when targeting Linux so this should be relatively easy to fix. We probably wrongly assume that only MSVC will be used on Windows in our cmake script. I can take a closer look at it in a few days when I get back home.

**Comment by ianichitei** [comment]
Hi! I'm guessing you're compiling for Windows. I haven't really used anything besides MSVC for Windows, but we support clang and GCC when targeting Linux so this should be relatively easy to fix. We probably wrongly assume that only MSVC will be used on Windows in our cmake script. I can take a closer look at it in a few days when I get back home.

**Comment by angelfor3v3r** [comment]
Yea, I'm compiling for windows. If you need more details I'm willing to provide them to the best of my ability. I was using the latest version of clang/clang-cl/etc that you can get from the Visual Studio installer. GCC on windows I don't have too much knowledge with though.
