### ISSUE TITLE
Add port for vcpkg

### ISSUE THREAD

**Issue by Nomade040** [bitdefender/bddisasm#8]
Hello, I think this project would be more accessible if present in [vcpkg](https://github.com/microsoft/vcpkg).

Cheers.

**Comment by ianichitei** [comment]
Hello. This sounds like a nice thing to have. 

I looked a bit over vcpkg [docs](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md) and it looks like we need a tagged release in order to be able to add it to vcpkg. We don't have a tagged release, yet, but we are working on making one. 

I'll get back to this once that is done.

**Comment by ianichitei** [comment]
I looked a bit more over the docs and and I'm wondering how useful it would be for vcpkg users. bddisasm is not using cmake for builds, and vcpkg seems to be built around that. For Linux builds I can probably generate a pkgconfig file at build/install time and cmake users can use `pkg_check_modules` to get the required build information.

@Nomade040 do you have a specific use case in mind?

**Comment by Nomade040** [comment]
My bad, I didn't know that vcpkg required cmake and bddisasm doesn't use it. Vcpkg is really helpful for me because you just install a library once and at least on Visual studio which is my main IDE I just #include whatever library I had previously installed.

**Comment by ianichitei** [comment]
> My bad, I didn't know that vcpkg required cmake and bddisasm doesn't use it. Vcpkg is really helpful for me because you just install a library once and at least on Visual studio which is my main IDE I just #include whatever library I had previously installed.

This is easy to handle and it looks like it does not need any kind of special treatment.

**Comment by 0479010347** [comment]
I think I have been hacked is there anyway you can get rid off the hack?🙏

**Comment by ianichitei** [comment]
microsoft/vcpkg#18046 which adds a port for bddisasm was just merged. I may also take a look at [Conan](https://conan.io/) in the future, but for now I'm going to close this issue.
