### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by turol** [bitdefender/bddisasm#89]
Comment references `ND_OP_REL_OFFS`
https://github.com/bitdefender/bddisasm/blob/f32c0373acb4314db364399aaf27f6560806fe58/inc/bdx86_core.h#L887

There is no such thing, it's called `ND_OP_OFFS`
https://github.com/bitdefender/bddisasm/blob/f32c0373acb4314db364399aaf27f6560806fe58/inc/bdx86_core.h#L474

**Comment by vlutas** [comment]
Fixed in the latest commit.

Thanks for pointing this out!
