### ISSUE TITLE
bddisasm leaks mnemonic string table

### ISSUE THREAD

**Issue by ScimitarEnjoyer** [bitdefender/bddisasm#97]
The mnemonic string table `gMnemonics` is present even if `BDDISASM_NO_FORMAT` is defined.

Please consider adding a define that removes the mnemonics table entirely and sets the `Instrux::Mnemonic` field to `ND_NULL` (or an empty string). Having a numeric representation of the mnemonic (like `ZydisMnemonic`) alongside (or instead of) the text representation would be ideal.

```c
static NDSTATUS
NdCopyInstructionInfo(
    INSTRUX *Instrux,
    ND_IDBE *Idbe
    )
{
    Instrux->Mnemonic = gMnemonics[Idbe->Mnemonic];
    ...
````

**Comment by ianichitei** [comment]
Hi!

There is already a unique ID for each instruction: `INSTRUX::Instruction`. Note that these values may change between `bddisasm` versions.

I assume you'd like to compile out the strings in order to save memory?

**Comment by ScimitarEnjoyer** [comment]
Hello :)

Yeah, I wanted to remove the strings from the binary and I think this would be nice to have in the official distribution.

Regarding the mnemonics, my suggestion was having the index into the table be defined as an enumeration so users can still work with the mnemonic if needed without having the entire string table in the binary.

**Comment by akisari** [comment]
The `BDDISASM_NO_MNEMONIC` define was added in commit  [4026e76](https://github.com/bitdefender/bddisasm/commit/4026e7610fe739b0a16b8891cb7f4f9aa7724f28) to no longer include information about mnemonics.
